apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: carrier-capacity-consumption
  # This is an extra long description with Markdown
  description: |
    Carrier Capacity is a consumer application
  links:
    - url: https://github.com/prabhu-sunderaraman/for-backstage-sample-service
      title: Github repo
      icon: github
spec:
  type: consumer
  lifecycle: qa
  owner: MS
  system: occd
  dependsOn: ['resource:carrier-capacity-eventhub', 'resource:carrier-capacity-database']
  consumesApis: ['component:capacity-common-library']
