apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-pool-consumer
  # This is an extra long description with Markdown
  description: |
    Resource Pool is a consumer application
  links:
    - url: https://github.com/prabhu-sunderaraman/for-backstage-sample-service
      title: Github repo
      icon: github
spec:
  type: consumer
  lifecycle: qa
  owner: MS
  system: occd
  dependsOn: ['resource:resource-pool-eventhub']
  consumesApis: ['component:capacity-common-library']
