apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-component
  # This is an extra long description with Markdown
  description: |
    [Sample component](http://sample.com) is an example API
  links:
    - url: https://github.com/prabhu-sunderaraman/for-backstage-sample-service
      title: Github repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: sample-system
  dependsOn: ['component:sample2-component']
